repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2000']

  - repo: local
    hooks:
      - id: go-fmt
        name: go-fmt
        entry: gofmt -w
        language: system
        files: \.go$
        exclude: ^docs/SERVER_MODE/
      - id: go-imports
        name: go-imports
        entry: goimports -w
        language: system
        files: \.go$
        exclude: ^docs/SERVER_MODE/
      - id: go-mod-tidy
        name: go-mod-tidy
        entry: go mod tidy
        language: system
        files: go\.mod$
        pass_filenames: false
      - id: eslint
        name: eslint
        entry: powershell.exe -Command "cd frontend; npm run lint"
        language: system
        files: \.(js|ts|vue)$
        pass_filenames: false
